language: ruby
before_script:
- pip install --user awscli
- rm -rf public
- bundle exec jekyll build
script:
- aws s3 sync public/ s3://momistatic --acl pubic-read --delete
- aws cloudfront create-invalidation --distribution-id 
branches:
  only:
  - master