language: ruby
rvm:
 - 2.6.3
before_script:
- pip install --user awscli
- rm -rf public
- bundle exec jekyll build
script:
- aws s3 sync public/ s3://momistatic --acl public-read --delete
- aws cloudfront create-invalidation --distribution-id E1W9OHLBJXOU63 --paths '/*'

branches:
 only:
 - master